### ISSUE TITLE
Windows. Compilation error

### ISSUE THREAD

**Issue by Fliego** [Microsoft/nodejs-guidelines#73]
Windows 10 x64
Visual Studio 2017 installed, but node-gyp uses vs2015 (from windows-build-tools) and Python27 (from Anaconda).

```
C:\Users\Igor Igorevich Kim\Desktop\edge-react-gui-develop>npm i

> bcoin-native@0.0.23 install C:\Users\Igor Igorevich Kim\Desktop\edge-react-gui-develop\node_modules\bcoin-native
> node-gyp rebuild


C:\Users\Igor Igorevich Kim\Desktop\edge-react-gui-develop\node_modules\bcoin-native>if not defined npm_config_node_gyp (node "C:\Users\Igor Igorevich Kim\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Igor Igorevich Kim\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node_modules\node-gyp\bin\node-gyp.js" rebuild )
  poly1305-donna.c
  chacha20_simple.c
  insecure_memzero.c
  sha256.c
  crypto_scrypt.c
  chacha20.cc
  poly1305.cc
  digest.cc
  cipher.cc
  base58.cc
  bech32.cc
  scrypt.cc
  scrypt_async.cc
..\src\scrypt.cc(20): warning C4244: 'argument': conversion from 'uint64_t' to 'uint32_t', possible loss of data [C:\Users\Igor Igorevich Kim\Desktop\edge-react-gui-develop\node_modules\bcoin-native\build\bcoin-native.vcxproj]
  murmur3.cc
  siphash.cc
  bcn.cc
..\src\scrypt_async.cc(59): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\Igor Igorevich Kim\
Desktop\edge-react-gui-develop\node_modules\bcoin-native\build\bcoin-native.vcxproj]
  C:\Users\Igor Igorevich Kim\Desktop\edge-react-gui-develop\node_modules\nan\nan.h(1618): note: see declaration of 'Nan::Callback::Call' win_delay_load_hook.cc
     Creating library C:\Users\Igor Igorevich Kim\Desktop\edge-react-gui-develop\node_modules\bcoin-native\build\Release\bcoin-native.lib and object C:\Users\Igor Igorevich Kim\Desktop\edge-react-gui-develop\node_modules\bcoin-native\build\Release\bcoin-native.exp
digest.obj : error LNK2001: unresolved external symbol RIPEMD160_Update [C:\Users\Igor Igorevich Kim\Desktop\edge-react-gui-develop\node_modules\bcoin-native\build\bcoin-native.vcxproj]
digest.obj : error LNK2001: unresolved external symbol RIPEMD160_Init [C:\Users\Igor Igorevich Kim\Desktop\edge-react-gui-develop\node_modules\bcoin-native\build\bcoin-native.vcxproj]
digest.obj : error LNK2001: unresolved external symbol RIPEMD160_Final [C:\Users\Igor Igorevich Kim\Desktop\edge-react-gui-develop\node_modules\bcoin-native\build\bcoin-native.vcxproj]
C:\Users\Igor Igorevich Kim\Desktop\edge-react-gui-develop\node_modules\bcoin-native\build\Release\bcoin-native.node :
fatal error LNK1120: 3 unresolved externals [C:\Users\Igor Igorevich Kim\Desktop\edge-react-gui-develop\node_modules\bcoin-native\build\bcoin-native.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Igor Igorevich Kim\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Igor Igorevich Kim\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\npm-lifecycle\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Igor Igorevich Kim\Desktop\edge-react-gui-develop\node_modules\bcoin-native
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
```

**Comment by mjbvz** [comment]
Sorry but this is not the correct repo for this. Please try asking on StackOverflow or following up with whatever component is causing this error
